INSERT IGNORE INTO m_permission VALUES (null, 'inventory', 'LIST_ITEMDETAILS', 'ITEMDETAILS', 'LIST', '0');
INSERT IGNORE INTO m_permission VALUES (null, 'crm', 'LIST_TICKET', 'TICKET', 'LIST', '0');
INSERT IGNORE INTO m_permission VALUES (null, 'crm', 'LIST_PROSPECT', 'PROSPECT', 'LIST', '0');
INSERT IGNORE INTO m_permission VALUES (null, 'inventory', 'CREATE_MODELPROVISIONMAPPING', 'MODELPROVISIONMAPPING', 'CREATE', '0');
INSERT IGNORE INTO m_permission VALUES (null, 'inventory', 'READ_MODELPROVISIONMAPPING', 'MODELPROVISIONMAPPING', 'READ', '0');
INSERT IGNORE INTO m_permission VALUES (null, 'inventory', 'UPDATE_MODELPROVISIONMAPPING', 'MODELPROVISIONMAPPING', 'UPDATE', '0');
INSERT IGNORE INTO m_permission VALUES (null, 'inventory', 'DELETE_MODELPROVISIONMAPPING', 'MODELPROVISIONMAPPING', 'DELETE', '0');
INSERT IGNORE INTO m_permission VALUES (null, 'portfolio', 'LIST_CLIENTS', 'CLIENTS', 'LIST', '0');

