Update m_code set module = 'Provisioning' where id=13;
Update m_code set module = 'Media' where id=19;
Update m_code set module = 'Client' where id=64;
Update m_code set module = 'Client' where id=65;
Update m_code set module = 'Client' where id=66;
Update m_code set module = 'Service' where id=71;
Update m_code set module = 'Master' where id=72;
Update m_code set module = 'Master' where id=73;
Update m_code set module = 'Master' where id=74;
Update m_code set module = 'Service' where id=75;
Update m_code set module = 'Client' where id=76;
Update c_configuration set value='emailId@domain.com' where id=47;
Update c_configuration set module='Administrator' where id=64;
Update m_permission set `grouping` ='Accounting' where id=1036;
Update m_permission set `grouping` ='Accounting' where id=650;
Update m_permission set `grouping` ='Accounting' where id=482;
Update m_permission set `grouping` ='Accounting' where id=483;
Update m_permission set `grouping` ='Accounting' where id=484;
Update m_permission set `grouping` ='Accounting' where id=257;
Update m_permission set `grouping` ='Accounting' where id=258;
Update m_permission set `grouping` ='Accounting' where id=259;
Update m_permission set `grouping` ='Accounting' where id=651;
Update m_permission set `grouping` ='Accounting' where id=260;
Update m_permission set `grouping` ='Accounting' where id=261;
Update m_permission set `grouping` ='Accounting' where id=262;
Update m_permission set `grouping` ='Accounting' where id=652;
Update m_permission set `grouping` ='Service/Order' where id=366;
Update m_permission set `grouping` ='Service/Order' where id=628;
Update m_permission set `grouping` ='Service/Order' where id=382;
Update m_permission set `grouping` ='Service/Order' where id=383;
Update m_permission set `grouping` ='Master/Others' where id=586;
Update m_permission set `grouping` ='Master/Others' where id=588;
Update m_permission set `grouping` ='Master/Others' where id=589;
Update m_permission set `grouping` ='Master/Others' where id=624;
Update m_permission set `grouping` ='Master/Others' where id=954;
Update m_permission set `grouping` ='Batch' where id=611;
Update m_permission set `grouping` ='Batch' where id=623;
Update m_permission set `grouping` ='Batch' where id=659;
Update m_permission set `grouping` ='Batch' where id=532;
Update m_permission set `grouping` ='Batch' where id=558;
Update m_permission set `grouping` ='Batch' where id=559;
Update m_permission set `grouping` ='Batch' where id=643;
Update m_permission set `grouping` ='Batch' where id=563;
Update m_permission set `grouping` ='Batch' where id=787;
Update m_permission set `grouping` ='Batch' where id=797;
Update m_permission set `grouping` ='Batch' where id=419;
Update m_permission set `grouping` ='Check_Remove' where id=606;
Update m_permission set `grouping` ='Check_Remove' where id=607;
Update m_permission set `grouping` ='Check_Remove' where id=608;
Update m_permission set `grouping` ='Check_Remove' where id=625;
Update m_permission set `grouping` ='Check_Remove' where id=734;
Update m_permission set `grouping` ='Check_Remove' where id=771;
Update m_permission set `grouping` ='Check_Remove' where id=615;
Update m_permission set `grouping` ='Check_Remove' where id=616;
Update m_permission set `grouping` ='Check_Remove' where id=709;
Update m_permission set `grouping` ='Check_Remove' where id=762;
Update m_permission set `grouping` ='Check_Remove' where id=710;
Update m_permission set `grouping` ='CRM' where id=1054;
Update m_permission set `grouping` ='CRM' where id=927;
Update m_permission set `grouping` ='CRM' where id=928;
Update m_permission set `grouping` ='CRM' where id=929;
Update m_permission set `grouping` ='CRM' where id=930;
Update m_permission set `grouping` ='CRM' where id=931;
Update m_permission set `grouping` ='CRM' where id=932;
Update m_permission set `grouping` ='CRM' where id=1053;
Update m_permission set `grouping` ='CRM' where id=357;
Update m_permission set `grouping` ='CRM' where id=358;
Update m_permission set `grouping` ='CRM' where id=359;
Update m_permission set `grouping` ='CRM' where id=641;
Update m_permission set `grouping` ='Customer' where id=110;
Update m_permission set `grouping` ='Customer' where id=111;
Update m_permission set `grouping` ='Customer' where id=113;
Update m_permission set `grouping` ='Customer' where id=115;
Update m_permission set `grouping` ='Customer' where id=714;
Update m_permission set `grouping` ='Customer' where id=508;
Update m_permission set `grouping` ='Customer' where id=277;
Update m_permission set `grouping` ='Customer' where id=885;
Update m_permission set `grouping` ='Customer' where id=886;
Update m_permission set `grouping` ='Customer' where id=448;
Update m_permission set `grouping` ='Customer' where id=712;
Update m_permission set `grouping` ='Customer' where id=1051;
Update m_permission set `grouping` ='Customer' where id=673;
Update m_permission set `grouping` ='Customer' where id=674;
Update m_permission set `grouping` ='Customer' where id=689;
Update m_permission set `grouping` ='Customer' where id=157;
Update m_permission set `grouping` ='Customer' where id=158;
Update m_permission set `grouping` ='Customer' where id=160;
Update m_permission set `grouping` ='Customer' where id=162;
Update m_permission set `grouping` ='Customer' where id=117;
Update m_permission set `grouping` ='Customer' where id=118;
Update m_permission set `grouping` ='Customer' where id=120;
Update m_permission set `grouping` ='Customer' where id=733;
Update m_permission set `grouping` ='Customer' where id=122;
Update m_permission set `grouping` ='Customer' where id=123;
Update m_permission set `grouping` ='Customer' where id=125;
Update m_permission set `grouping` ='Customer' where id=127;
Update m_permission set `grouping` ='Customer' where id=1059;
Update m_permission set `grouping` ='Customer' where id=703;
Update m_permission set `grouping` ='Customer' where id=742;
Update m_permission set `grouping` ='Customer' where id=744;
Update m_permission set `grouping` ='Customer' where id=745;
Update m_permission set `grouping` ='Customer' where id=747;
Update m_permission set `grouping` ='Customer' where id=634;
Update m_permission set `grouping` ='Customer' where id=470;
Update m_permission set `grouping` ='Customer' where id=471;
Update m_permission set `grouping` ='Customer' where id=472;
Update m_permission set `grouping` ='Customer' where id=644;
Update m_permission set `grouping` ='Customer' where id=420;
Update m_permission set `grouping` ='Customer' where id=449;
Update m_permission set `grouping` ='Customer' where id=453;
Update m_permission set `grouping` ='Customer' where id=454;
Update m_permission set `grouping` ='Customer' where id=769;
Update m_permission set `grouping` ='Customer' where id=862;
Update m_permission set `grouping` ='Device' where id=1025;
Update m_permission set `grouping` ='Device' where id=576;
Update m_permission set `grouping` ='Device' where id=577;
Update m_permission set `grouping` ='Device' where id=355;
Update m_permission set `grouping` ='Device' where id=356;
Update m_permission set `grouping` ='Device' where id=424;
Update m_permission set `grouping` ='Device' where id=609;
Update m_permission set `grouping` ='Device' where id=408;
Update m_permission set `grouping` ='Device' where id=450;
Update m_permission set `grouping` ='Device' where id=796;
Update m_permission set `grouping` ='Device' where id=610;
Update m_permission set `grouping` ='Device' where id=388;
Update m_permission set `grouping` ='Device' where id=461;
Update m_permission set `grouping` ='Device' where id=573;
Update m_permission set `grouping` ='Device' where id=574;
Update m_permission set `grouping` ='Device' where id=584;
Update m_permission set `grouping` ='Device' where id=632;
Update m_permission set `grouping` ='Finance' where id=346;
Update m_permission set `grouping` ='Finance' where id=347;
Update m_permission set `grouping` ='Finance' where id=348;
Update m_permission set `grouping` ='Finance' where id=649;
Update m_permission set `grouping` ='Finance' where id=343;
Update m_permission set `grouping` ='Finance' where id=344;
Update m_permission set `grouping` ='Finance' where id=345;
Update m_permission set `grouping` ='Finance' where id=423;
Update m_permission set `grouping` ='Finance' where id=425;
Update m_permission set `grouping` ='Finance' where id=263;
Update m_permission set `grouping` ='Finance' where id=264;
Update m_permission set `grouping` ='Finance' where id=653;
Update m_permission set `grouping` ='Finance' where id=590;
Update m_permission set `grouping` ='Finance' where id=340;
Update m_permission set `grouping` ='Finance' where id=341;
Update m_permission set `grouping` ='Finance' where id=342;
Update m_permission set `grouping` ='Finance' where id=422;
Update m_permission set `grouping` ='Finance' where id=690;
Update m_permission set `grouping` ='Finance' where id=802;
Update m_permission set `grouping` ='Finance' where id=583;
Update m_permission set `grouping` ='Finance' where id=591;
Update m_permission set `grouping` ='Finance' where id=633;
Update m_permission set `grouping` ='Finance' where id=989;
Update m_permission set `grouping` ='Finance' where id=990;
Update m_permission set `grouping` ='Finance' where id=991;
Update m_permission set `grouping` ='Finance' where id=349;
Update m_permission set `grouping` ='Finance' where id=350;
Update m_permission set `grouping` ='Finance' where id=351;
Update m_permission set `grouping` ='Finance' where id=993;
Update m_permission set `grouping` ='Finance' where id=393;
Update m_permission set `grouping` ='Finance' where id=394;
Update m_permission set `grouping` ='Finance' where id=397;
Update m_permission set `grouping` ='Finance' where id=352;
Update m_permission set `grouping` ='Finance' where id=353;
Update m_permission set `grouping` ='Finance' where id=354;
Update m_permission set `grouping` ='Finance' where id=426;
Update m_permission set `grouping` ='General' where id=711;
Update m_permission set `grouping` ='General' where id=713;
Update m_permission set `grouping` ='General' where id=830;
Update m_permission set `grouping` ='General' where id=41;
Update m_permission set `grouping` ='General' where id=630;
Update m_permission set `grouping` ='General' where id=629;
Update m_permission set `grouping` ='Inventory' where id=387;
Update m_permission set `grouping` ='Inventory' where id=647;
Update m_permission set `grouping` ='Inventory' where id=761;
Update m_permission set `grouping` ='Inventory' where id=595;
Update m_permission set `grouping` ='Inventory' where id=360;
Update m_permission set `grouping` ='Inventory' where id=361;
Update m_permission set `grouping` ='Inventory' where id=362;
Update m_permission set `grouping` ='Inventory' where id=460;
Update m_permission set `grouping` ='Inventory' where id=330;
Update m_permission set `grouping` ='Inventory' where id=331;
Update m_permission set `grouping` ='Inventory' where id=332;
Update m_permission set `grouping` ='Inventory' where id=431;
Update m_permission set `grouping` ='Inventory' where id=1052;
Update m_permission set `grouping` ='Inventory' where id=657;
Update m_permission set `grouping` ='Inventory' where id=646;
Update m_permission set `grouping` ='Inventory' where id=672;
Update m_permission set `grouping` ='Inventory' where id=473;
Update m_permission set `grouping` ='Inventory' where id=475;
Update m_permission set `grouping` ='Inventory' where id=645;
Update m_permission set `grouping` ='Inventory' where id=794;
Update m_permission set `grouping` ='Inventory' where id=779;
Update m_permission set `grouping` ='Inventory' where id=640;
Update m_permission set `grouping` ='Inventory' where id=474;
Update m_permission set `grouping` ='Master/Core' where id=638;
Update m_permission set `grouping` ='Master/Core' where id=465;
Update m_permission set `grouping` ='Master/Core' where id=467;
Update m_permission set `grouping` ='Master/Core' where id=468;
Update m_permission set `grouping` ='Master/Core' where id=363;
Update m_permission set `grouping` ='Master/Core' where id=333;
Update m_permission set `grouping` ='Master/Core' where id=334;
Update m_permission set `grouping` ='Master/Core' where id=335;
Update m_permission set `grouping` ='Master/Core' where id=447;
Update m_permission set `grouping` ='Master/Core' where id=365;
Update m_permission set `grouping` ='Master/Core' where id=409;
Update m_permission set `grouping` ='Master/Core' where id=412;
Update m_permission set `grouping` ='Master/Core' where id=413;
Update m_permission set `grouping` ='Master/Core' where id=436;
Update m_permission set `grouping` ='Master/Core' where id=1050;
Update m_permission set `grouping` ='Master/Core' where id=38;
Update m_permission set `grouping` ='Master/Core' where id=39;
Update m_permission set `grouping` ='Master/Core' where id=43;
Update m_permission set `grouping` ='Master/Core' where id=44;
Update m_permission set `grouping` ='Master/Core' where id=46;
Update m_permission set `grouping` ='Master/Core' where id=487;
Update m_permission set `grouping` ='Master/Core' where id=489;
Update m_permission set `grouping` ='Master/Core' where id=491;
Update m_permission set `grouping` ='Master/Core' where id=863;
Update m_permission set `grouping` ='Master/Core' where id=865;
Update m_permission set `grouping` ='Master/Core' where id=866;
Update m_permission set `grouping` ='Master/Core' where id=884;
Update m_permission set `grouping` ='Master/Core' where id=992;
Update m_permission set `grouping` ='Master/Core' where id=985;
Update m_permission set `grouping` ='Master/Core' where id=986;
Update m_permission set `grouping` ='Master/Core' where id=987;
Update m_permission set `grouping` ='Master/Core' where id=988;
Update m_permission set `grouping` ='Master/Core' where id=832;
Update m_permission set `grouping` ='Master/Core' where id=834;
Update m_permission set `grouping` ='Master/Core' where id=835;
Update m_permission set `grouping` ='Master/Others' where id=321;
Update m_permission set `grouping` ='Master/Others' where id=322;
Update m_permission set `grouping` ='Master/Others' where id=323;
Update m_permission set `grouping` ='Master/Others' where id=428;
Update m_permission set `grouping` ='Master/Others' where id=391;
Update m_permission set `grouping` ='Master/Others' where id=392;
Update m_permission set `grouping` ='Master/Others' where id=396;
Update m_permission set `grouping` ='Master/Others' where id=1005;
Update m_permission set `grouping` ='Master/Others' where id=1006;
Update m_permission set `grouping` ='Master/Others' where id=1007;
Update m_permission set `grouping` ='Master/Others' where id=1008;
Update m_permission set `grouping` ='Master/Others' where id=1009;
Update m_permission set `grouping` ='Master/Others' where id=1010;
Update m_permission set `grouping` ='Master/Others' where id=1011;
Update m_permission set `grouping` ='Master/Others' where id=1012;
Update m_permission set `grouping` ='Master/Others' where id=1017;
Update m_permission set `grouping` ='Master/Others' where id=1018;
Update m_permission set `grouping` ='Master/Others' where id=1019;
Update m_permission set `grouping` ='Master/Others' where id=1020;
Update m_permission set `grouping` ='Master/Others' where id=21;
Update m_permission set `grouping` ='Master/Others' where id=22;
Update m_permission set `grouping` ='Master/Others' where id=668;
Update m_permission set `grouping` ='Master/Others' where id=715;
Update m_permission set `grouping` ='Master/Others' where id=622;
Update m_permission set `grouping` ='Master/Others' where id=648;
Update m_permission set `grouping` ='Master/Others' where id=691;
Update m_permission set `grouping` ='Master/Others' where id=561;
Update m_permission set `grouping` ='Master/Others' where id=980;
Update m_permission set `grouping` ='Master/Others' where id=981;
Update m_permission set `grouping` ='Master/Others' where id=982;
Update m_permission set `grouping` ='Master/Others' where id=983;
Update m_permission set `grouping` ='Master/Others' where id=984;
Update m_permission set `grouping` ='Master/Others' where id=1030;
Update m_permission set `grouping` ='Master/Others' where id=1031;
Update m_permission set `grouping` ='Master/Others' where id=1032;
Update m_permission set `grouping` ='Master/Others' where id=1033;
Update m_permission set `grouping` ='Master/Others' where id=776;
Update m_permission set `grouping` ='Master/Others' where id=728;
Update m_permission set `grouping` ='Master/Others' where id=731;
Update m_permission set `grouping` ='Master/Others' where id=732;
Update m_permission set `grouping` ='Master/Others' where id=24;
Update m_permission set `grouping` ='Master/Others' where id=25;
Update m_permission set `grouping` ='Master/Others' where id=27;
Update m_permission set `grouping` ='Master/Others' where id=29;
Update m_permission set `grouping` ='Master/Others' where id=31;
Update m_permission set `grouping` ='Master/Others' where id=32;
Update m_permission set `grouping` ='Master/Others' where id=34;
Update m_permission set `grouping` ='Master/Others' where id=36;
Update m_permission set `grouping` ='Master/Others' where id=410;
Update m_permission set `grouping` ='Master/Others' where id=411;
Update m_permission set `grouping` ='Master/Others' where id=432;
Update m_permission set `grouping` ='Master/Others' where id=367;
Update m_permission set `grouping` ='Master/Others' where id=626;
Update m_permission set `grouping` ='Master/Others' where id=372;
Update m_permission set `grouping` ='Master/Others' where id=384;
Update m_permission set `grouping` ='Master/Others' where id=386;
Update m_permission set `grouping` ='Master/Others' where id=374;
Update m_permission set `grouping` ='Master/Others' where id=631;
Update m_permission set `grouping` ='Master/Others' where id=458;
Update m_permission set `grouping` ='Master/Others' where id=459;
Update m_permission set `grouping` ='Master/Others' where id=778;
Update m_permission set `grouping` ='Master/Others' where id=894;
Update m_permission set `grouping` ='Master/Others' where id=702;
Update m_permission set `grouping` ='Master/Others' where id=655;
Update m_permission set `grouping` ='Master/Others' where id=400;
Update m_permission set `grouping` ='Master/Others' where id=401;
Update m_permission set `grouping` ='Master/Others' where id=402;
Update m_permission set `grouping` ='Master/Others' where id=434;
Update m_permission set `grouping` ='Master/Others' where id=78;
Update m_permission set `grouping` ='Master/Others' where id=79;
Update m_permission set `grouping` ='Master/Others' where id=81;
Update m_permission set `grouping` ='Master/Others' where id=669;
Update m_permission set `grouping` ='Master/Others' where id=670;
Update m_permission set `grouping` ='Master/Others' where id=667;
Update m_permission set `grouping` ='Master/Others' where id=1034;
Update m_permission set `grouping` ='Master/Others' where id=469;
Update m_permission set `grouping` ='Master/Others' where id=798;
Update m_permission set `grouping` ='Master/Others' where id=799;
Update m_permission set `grouping` ='Master/Others' where id=800;
Update m_permission set `grouping` ='Master/Others' where id=324;
Update m_permission set `grouping` ='Master/Others' where id=325;
Update m_permission set `grouping` ='Master/Others' where id=326;
Update m_permission set `grouping` ='Master/Others' where id=430;
Update m_permission set `grouping` ='Master/Others' where id=327;
Update m_permission set `grouping` ='Master/Others' where id=328;
Update m_permission set `grouping` ='Master/Others' where id=329;
Update m_permission set `grouping` ='Master/Others' where id=452;
Update m_permission set `grouping` ='Master/Others' where id=1024;
Update m_permission set `grouping` ='Master/Others' where id=1021;
Update m_permission set `grouping` ='Master/Others' where id=1022;
Update m_permission set `grouping` ='Master/Others' where id=1023;
Update m_permission set `grouping` ='Master/Others' where id=1037;
Update m_permission set `grouping` ='Master/Others' where id=1038;
Update m_permission set `grouping` ='Master/Others' where id=1039;
Update m_permission set `grouping` ='Master/Others' where id=1040;
Update m_permission set `grouping` ='Master/Others' where id=1041;
Update m_permission set `grouping` ='Master/Others' where id=1042;
Update m_permission set `grouping` ='Master/Others' where id=1043;
Update m_permission set `grouping` ='Master/Others' where id=1044;
Update m_permission set `grouping` ='Master/Others' where id=1045;
Update m_permission set `grouping` ='Master/Others' where id=1046;
Update m_permission set `grouping` ='Master/Others' where id=1047;
Update m_permission set `grouping` ='Master/Others' where id=1048;
Update m_permission set `grouping` ='Master/Others' where id=599;
Update m_permission set `grouping` ='Master/Others' where id=600;
Update m_permission set `grouping` ='Master/Others' where id=602;
Update m_permission set `grouping` ='Master/Others' where id=635;
Update m_permission set `grouping` ='Master/Others' where id=811;
Update m_permission set `grouping` ='Master/Others' where id=318;
Update m_permission set `grouping` ='Master/Others' where id=319;
Update m_permission set `grouping` ='Master/Others' where id=320;
Update m_permission set `grouping` ='Master/Others' where id=429;
Update m_permission set `grouping` ='Master/Others' where id=569;
Update m_permission set `grouping` ='Master/Others' where id=570;
Update m_permission set `grouping` ='Master/Others' where id=639;
Update m_permission set `grouping` ='Master/Others' where id=887;
Update m_permission set `grouping` ='Master/Others' where id=1016;
Update m_permission set `grouping` ='Master/Others' where id=854;
Update m_permission set `grouping` ='Master/Others' where id=855;
Update m_permission set `grouping` ='Master/Others' where id=856;
Update m_permission set `grouping` ='Master/Others' where id=860;
Update m_permission set `grouping` ='Master/Others' where id=861;
Update m_permission set `grouping` ='Master/Others' where id=857;
Update m_permission set `grouping` ='Master/Others' where id=858;
Update m_permission set `grouping` ='Master/Others' where id=859;
Update m_permission set `grouping` ='Master/Others' where id=815;
Update m_permission set `grouping` ='Master/Others' where id=816;
Update m_permission set `grouping` ='Master/Others' where id=852;
Update m_permission set `grouping` ='Master/Others' where id=637;
Update m_permission set `grouping` ='Master/Others' where id=698;
Update m_permission set `grouping` ='Master/Others' where id=476;
Update m_permission set `grouping` ='Partner' where id=812;
Update m_permission set `grouping` ='Partner' where id=824;
Update m_permission set `grouping` ='Partner' where id=828;
Update m_permission set `grouping` ='Partner' where id=813;
Update m_permission set `grouping` ='Partner' where id=831;
Update m_permission set `grouping` ='Partner' where id=829;
Update m_permission set `grouping` ='Partner' where id=814;
Update m_permission set `grouping` ='Provisioning' where id=560;
Update m_permission set `grouping` ='Provisioning' where id=1026;
Update m_permission set `grouping` ='Provisioning' where id=1027;
Update m_permission set `grouping` ='Provisioning' where id=1028;
Update m_permission set `grouping` ='Provisioning' where id=1029;
Update m_permission set `grouping` ='Provisioning' where id=801;
Update m_permission set `grouping` ='Provisioning' where id=770;
Update m_permission set `grouping` ='Provisioning' where id=701;
Update m_permission set `grouping` ='Provisioning' where id=1004;
Update m_permission set `grouping` ='Provisioning' where id=656;
Update m_permission set `grouping` ='Provisioning' where id=579;
Update m_permission set `grouping` ='Provisioning' where id=581;
Update m_permission set `grouping` ='Provisioning' where id=582;
Update m_permission set `grouping` ='Provisioning' where id=853;
Update m_permission set `grouping` ='Provisioning' where id=621;
Update m_permission set `grouping` ='Remove' where id=848;
Update m_permission set `grouping` ='Remove' where id=849;
Update m_permission set `grouping` ='Remove' where id=806;
Update m_permission set `grouping` ='Remove' where id=807;
Update m_permission set `grouping` ='Remove' where id=808;
Update m_permission set `grouping` ='Remove' where id=995;
Update m_permission set `grouping` ='Remove' where id=827;
Update m_permission set `grouping` ='Remove' where id=997;
Update m_permission set `grouping` ='Remove' where id=998;
Update m_permission set `grouping` ='Remove' where id=49;
Update m_permission set `grouping` ='Remove' where id=50;
Update m_permission set `grouping` ='Remove' where id=51;
Update m_permission set `grouping` ='Remove' where id=52;
Update m_permission set `grouping` ='Remove' where id=548;
Update m_permission set `grouping` ='Remove' where id=549;
Update m_permission set `grouping` ='Remove' where id=550;
Update m_permission set `grouping` ='Remove' where id=551;
Update m_permission set `grouping` ='Remove' where id=552;
Update m_permission set `grouping` ='Remove' where id=553;
Update m_permission set `grouping` ='Remove' where id=554;
Update m_permission set `grouping` ='Remove' where id=555;
Update m_permission set `grouping` ='Remove' where id=312;
Update m_permission set `grouping` ='Remove' where id=313;
Update m_permission set `grouping` ='Remove' where id=112;
Update m_permission set `grouping` ='Remove' where id=114;
Update m_permission set `grouping` ='Remove' where id=116;
Update m_permission set `grouping` ='Remove' where id=506;
Update m_permission set `grouping` ='Remove' where id=507;
Update m_permission set `grouping` ='Remove' where id=159;
Update m_permission set `grouping` ='Remove' where id=161;
Update m_permission set `grouping` ='Remove' where id=163;
Update m_permission set `grouping` ='Remove' where id=119;
Update m_permission set `grouping` ='Remove' where id=121;
Update m_permission set `grouping` ='Remove' where id=124;
Update m_permission set `grouping` ='Remove' where id=126;
Update m_permission set `grouping` ='Remove' where id=128;
Update m_permission set `grouping` ='Remove' where id=750;
Update m_permission set `grouping` ='Remove' where id=753;
Update m_permission set `grouping` ='Remove' where id=755;
Update m_permission set `grouping` ='Remove' where id=743;
Update m_permission set `grouping` ='Remove' where id=746;
Update m_permission set `grouping` ='Remove' where id=748;
Update m_permission set `grouping` ='Remove' where id=994;
Update m_permission set `grouping` ='Remove' where id=804;
Update m_permission set `grouping` ='Remove' where id=89;
Update m_permission set `grouping` ='Remove' where id=90;
Update m_permission set `grouping` ='Remove' where id=92;
Update m_permission set `grouping` ='Remove' where id=94;
Update m_permission set `grouping` ='Remove' where id=364;
Update m_permission set `grouping` ='Remove' where id=294;
Update m_permission set `grouping` ='Remove' where id=505;
Update m_permission set `grouping` ='Remove' where id=809;
Update m_permission set `grouping` ='Remove' where id=972;
Update m_permission set `grouping` ='Remove' where id=872;
Update m_permission set `grouping` ='Remove' where id=875;
Update m_permission set `grouping` ='Remove' where id=883;
Update m_permission set `grouping` ='Remove' where id=571;
Update m_permission set `grouping` ='Remove' where id=572;
Update m_permission set `grouping` ='Remove' where id=654;
Update m_permission set `grouping` ='Reports' where id=575;
Update m_permission set `grouping` ='Reports' where id=439;
Update m_permission set `grouping` ='Reports' where id=513;
Update m_permission set `grouping` ='Reports' where id=604;
Update m_permission set `grouping` ='Reports' where id=441;
Update m_permission set `grouping` ='Reports' where id=279;
Update m_permission set `grouping` ='Reports' where id=280;
Update m_permission set `grouping` ='Reports' where id=562;
Update m_permission set `grouping` ='Reports' where id=463;
Update m_permission set `grouping` ='Reports' where id=846;
Update m_permission set `grouping` ='Reports' where id=605;
Update m_permission set `grouping` ='Reports' where id=462;
Update m_permission set `grouping` ='Reports' where id=464;
Update m_permission set `grouping` ='Reports' where id=847;
Update m_permission set `grouping` ='Reports' where id=564;
Update m_permission set `grouping` ='Reports' where id=810;
Update m_permission set `grouping` ='Reports' where id=438;
Update m_permission set `grouping` ='Reports' where id=511;
Update m_permission set `grouping` ='Reports' where id=516;
Update m_permission set `grouping` ='Reports' where id=601;
Update m_permission set `grouping` ='Reports' where id=594;
Update m_permission set `grouping` ='Reports' where id=442;
Update m_permission set `grouping` ='Reports' where id=443;
Update m_permission set `grouping` ='Reports' where id=845;
Update m_permission set `grouping` ='Reports' where id=444;
Update m_permission set `grouping` ='Reports' where id=445;
Update m_permission set `grouping` ='Reports' where id=427;
Update m_permission set `grouping` ='Reports' where id=446;
Update m_permission set `grouping` ='Reports' where id=440;
Update m_permission set `grouping` ='Selfcare' where id=766;
Update m_permission set `grouping` ='Selfcare' where id=772;
Update m_permission set `grouping` ='Selfcare' where id=773;
Update m_permission set `grouping` ='Selfcare' where id=803;
Update m_permission set `grouping` ='Selfcare' where id=466;
Update m_permission set `grouping` ='Selfcare' where id=764;
Update m_permission set `grouping` ='Selfcare' where id=765;
Update m_permission set `grouping` ='Selfcare' where id=889;
Update m_permission set `grouping` ='Selfcare' where id=893;
Update m_permission set `grouping` ='Selfcare' where id=699;
Update m_permission set `grouping` ='Service' where id=777;
Update m_permission set `grouping` ='Service' where id=578;
Update m_permission set `grouping` ='Service' where id=1002;
Update m_permission set `grouping` ='Service' where id=1003;
Update m_permission set `grouping` ='Service' where id=1013;
Update m_permission set `grouping` ='Service' where id=1014;
Update m_permission set `grouping` ='Service' where id=1015;
Update m_permission set `grouping` ='Service' where id=1001;
Update m_permission set `grouping` ='Service' where id=1049;
Update m_permission set `grouping` ='Service/Order' where id=768;
Update m_permission set `grouping` ='Service/Order' where id=566;
Update m_permission set `grouping` ='Service/Order' where id=336;
Update m_permission set `grouping` ='Service/Order' where id=592;
Update m_permission set `grouping` ='Service/Order' where id=337;
Update m_permission set `grouping` ='Service/Order' where id=593;
Update m_permission set `grouping` ='Service/Order' where id=338;
Update m_permission set `grouping` ='Service/Order' where id=613;
Update m_permission set `grouping` ='Service/Order' where id=389;
Update m_permission set `grouping` ='Service/Order' where id=390;
Update m_permission set `grouping` ='Service/Order' where id=414;
Update m_permission set `grouping` ='Service/Order' where id=964;
Update m_permission set `grouping` ='Service/Order' where id=716;
Update m_permission set `grouping` ='Service/Order' where id=996;
Update m_permission set `grouping` ='Service/Order' where id=767;
Update m_permission set `grouping` ='Service/Order' where id=339;
Update m_permission set `grouping` ='Service/Order' where id=612;
Update m_permission set `grouping` ='Service/Order' where id=614;
Update m_permission set `grouping` ='Service/Order' where id=1000;
Update m_permission set `grouping` ='Service/Order' where id=671;
Update m_permission set `grouping` ='Service/Order' where id=368;
Update m_permission set `grouping` ='Service/Order' where id=371;
Update m_permission set `grouping` ='Service/Order' where id=627;
Update m_permission set `grouping` ='Service/Order' where id=759;
Update m_permission set `grouping` ='Service/Order' where id=760;
Update m_permission set `grouping` ='System' where id=749;
Update m_permission set `grouping` ='System' where id=751;
Update m_permission set `grouping` ='System' where id=752;
Update m_permission set `grouping` ='System' where id=754;
Update m_permission set `grouping` ='System' where id=305;
Update m_permission set `grouping` ='System' where id=306;
Update m_permission set `grouping` ='System' where id=308;
Update m_permission set `grouping` ='System' where id=310;
Update m_permission set `grouping` ='System' where id=6;
Update m_permission set `grouping` ='System' where id=7;
Update m_permission set `grouping` ='System' where id=9;
Update m_permission set `grouping` ='System' where id=1035;
Update m_permission set `grouping` ='System' where id=48;
Update m_permission set `grouping` ='System' where id=675;
Update m_permission set `grouping` ='System' where id=14;
Update m_permission set `grouping` ='System' where id=16;
Update m_permission set `grouping` ='System' where id=17;
Update m_permission set `grouping` ='System' where id=19;
Update m_permission set `grouping` ='System' where id=585;
Update m_permission set `grouping` ='System' where id=596;
Update m_permission set `grouping` ='System' where id=603;
Update m_permission set `grouping` ='System' where id=642;

INSERT INTO `m_role` VALUES (4,'CSR','Customer Sales Representative');
Insert into m_role_permission values (4,110);
Insert into m_role_permission values (4,111);
Insert into m_role_permission values (4,113);
Insert into m_role_permission values (4,115);
Insert into m_role_permission values (4,117);
Insert into m_role_permission values (4,118);
Insert into m_role_permission values (4,120);
Insert into m_role_permission values (4,157);
Insert into m_role_permission values (4,158);
Insert into m_role_permission values (4,160);
Insert into m_role_permission values (4,162);
Insert into m_role_permission values (4,277);
Insert into m_role_permission values (4,333);
Insert into m_role_permission values (4,334);
Insert into m_role_permission values (4,335);
Insert into m_role_permission values (4,336);
Insert into m_role_permission values (4,337);
Insert into m_role_permission values (4,338);
Insert into m_role_permission values (4,339);
Insert into m_role_permission values (4,340);
Insert into m_role_permission values (4,341);
Insert into m_role_permission values (4,342);
Insert into m_role_permission values (4,346);
Insert into m_role_permission values (4,347);
Insert into m_role_permission values (4,348);
Insert into m_role_permission values (4,357);
Insert into m_role_permission values (4,358);
Insert into m_role_permission values (4,359);
Insert into m_role_permission values (4,360);
Insert into m_role_permission values (4,361);
Insert into m_role_permission values (4,362);
Insert into m_role_permission values (4,367);
Insert into m_role_permission values (4,368);
Insert into m_role_permission values (4,371);
Insert into m_role_permission values (4,372);
Insert into m_role_permission values (4,374);
Insert into m_role_permission values (4,382);
Insert into m_role_permission values (4,383);
Insert into m_role_permission values (4,384);
Insert into m_role_permission values (4,386);
Insert into m_role_permission values (4,387);
Insert into m_role_permission values (4,388);
Insert into m_role_permission values (4,389);
Insert into m_role_permission values (4,390);
Insert into m_role_permission values (4,408);
Insert into m_role_permission values (4,409);
Insert into m_role_permission values (4,410);
Insert into m_role_permission values (4,411);
Insert into m_role_permission values (4,412);
Insert into m_role_permission values (4,413);
Insert into m_role_permission values (4,414);
Insert into m_role_permission values (4,419);
Insert into m_role_permission values (4,420);
Insert into m_role_permission values (4,422);
Insert into m_role_permission values (4,423);
Insert into m_role_permission values (4,424);
Insert into m_role_permission values (4,425);
Insert into m_role_permission values (4,426);
Insert into m_role_permission values (4,427);
Insert into m_role_permission values (4,428);
Insert into m_role_permission values (4,429);
Insert into m_role_permission values (4,430);
Insert into m_role_permission values (4,431);
Insert into m_role_permission values (4,432);
Insert into m_role_permission values (4,434);
Insert into m_role_permission values (4,436);
Insert into m_role_permission values (4,447);
Insert into m_role_permission values (4,448);
Insert into m_role_permission values (4,449);
Insert into m_role_permission values (4,450);
Insert into m_role_permission values (4,469);
Insert into m_role_permission values (4,470);
Insert into m_role_permission values (4,471);
Insert into m_role_permission values (4,472);
Insert into m_role_permission values (4,473);
Insert into m_role_permission values (4,474);
Insert into m_role_permission values (4,475);
Insert into m_role_permission values (4,569);
Insert into m_role_permission values (4,570);
Insert into m_role_permission values (4,571);
Insert into m_role_permission values (4,572);
Insert into m_role_permission values (4,573);
Insert into m_role_permission values (4,574);
Insert into m_role_permission values (4,577);
Insert into m_role_permission values (4,592);
Insert into m_role_permission values (4,593);
Insert into m_role_permission values (4,595);
Insert into m_role_permission values (4,626);
Insert into m_role_permission values (4,627);
Insert into m_role_permission values (4,628);
Insert into m_role_permission values (4,629);
Insert into m_role_permission values (4,630);
Insert into m_role_permission values (4,631);
Insert into m_role_permission values (4,632);
Insert into m_role_permission values (4,639);
Insert into m_role_permission values (4,640);
Insert into m_role_permission values (4,641);
Insert into m_role_permission values (4,644);
Insert into m_role_permission values (4,645);
Insert into m_role_permission values (4,646);
Insert into m_role_permission values (4,647);
Insert into m_role_permission values (4,885);
Insert into m_role_permission values (4,886);
Insert into m_role_permission values (4,712);
Insert into m_role_permission values (4,1051);
Insert into m_role_permission values (4,673);
Insert into m_role_permission values (4,674);
Insert into m_role_permission values (4,689);
Insert into m_role_permission values (4,1002);
Insert into m_role_permission values (4,1003);
Insert into m_role_permission values (4,1013);
Insert into m_role_permission values (4,1014);
Insert into m_role_permission values (4,1015);
Insert into m_role_permission values (4,1001);
Insert into m_role_permission values (4,1049);
Insert into m_role_permission values (4,703);
Insert into m_role_permission values (4,355);
Insert into m_role_permission values (4,356);
Insert into m_role_permission values (4,566);
Insert into m_role_permission values (4,613);
Insert into m_role_permission values (4,716);
Insert into m_role_permission values (4,767);
Insert into m_role_permission values (4,768);
Insert into m_role_permission values (4,964);
Insert into m_role_permission values (4,996);
Insert into m_role_permission values (4,796);
Insert into m_role_permission values (4,466);
Insert into m_role_permission values (4,764);
Insert into m_role_permission values (4,765);
Insert into m_role_permission values (4,772);
Insert into m_role_permission values (4,773);
Insert into m_role_permission values (4,803);
Insert into m_role_permission values (4,699);
Insert into m_role_permission values (4,889);
Insert into m_role_permission values (4,893);
Insert into m_role_permission values (4,1053);
Insert into m_role_permission values (4,444);



